"""add generated_images table and link to messages

Revision ID: 441e23b56f3c
Revises: 614d0ac0bc3b
Create Date: 2026-09-19 15:06:14.781547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441e23b56f3c'
down_revision: Union[str, None] = '614d0ac0bc3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_images_user_id'), 'generated_images', ['user_id'], unique=False)
    op.add_column('messages', sa.Column('generated_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'generated_images', ['generated_image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'generated_image_id')
    op.drop_index(op.f('ix_generated_images_user_id'), table_name='generated_images')
    op.drop_table('generated_images')
    # ### end Alembic commands ###
